<template>
  <head>
    <meta charset="utf-8">
    <title>Jyotish Responsive HTML Template</title>
    <meta
      content="width=device-width, initial-scale=1.0"
      name="viewport"
    >
    <meta
      name="description"
      content="Jyotish"
    >
    <meta
      name="keywords"
      content="Jyotish"
    >
    <meta
      name="author"
      content=""
    >
    <meta
      name="MobileOptimized"
      content="320"
    >
    <!--start style -->
    <link
      rel="stylesheet"
      href="/css/animate.css"
    >
    <link
      rel="stylesheet"
      href="/css/bootstrap.min.css"
    >
    <link
      rel="stylesheet"
      href="/css/font-awesome.css"
    >
    <link
      rel="stylesheet"
      href="/css/fonts.css"
    >
    <link
      rel="stylesheet"
      href="/css/flaticon.css"
    >
    <link
      rel="stylesheet"
      type="text/css"
      href="/css/sign_flaticon.css"
    >
    <link
      rel="stylesheet"
      href="/css/owl.carousel.css"
    >
    <link
      rel="stylesheet"
      href="/css/owl.theme.default.css"
    >
    <link
      rel="stylesheet"
      href="/css/magnific-popup.css"
    >
    <link
      rel="stylesheet"
      href="/css/reset.css"
    >
    <link
      rel="stylesheet"
      href="/css/datepicker.css"
    >
    <link
      rel="stylesheet"
      href="/css/style.css"
    >
    <link
      rel="stylesheet"
      href="/css/responsive.css"
    >
    <!-- favicon links -->
    <link
      rel="shortcut icon"
      type="image/png"
      href="/images/header/favicon.ico"
    >
  </head>
</template>
