name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4
        with:
          submodules: true

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # 3️⃣ Install dependencies
      - name: Install Dependencies
        run: npm ci

      # 4️⃣ Build Vue app
      - name: Build App
        run: npm run build

      # 5️⃣ Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1.0.0
        with:
          azure_static_web_apps_api_token: ${{ secrets.MY_AZURE_STATIC_WEB_APPS_TOKEN }}
          action: "upload"
          app_location: "/"       
          output_location: "dist" 
          api_location: ""       
